### PR TITLE
Cleanup + PyDoc

### PR DESCRIPTION
**Pull request by RDIL**
# Cleanup + PyDoc  
Documented almost everything, rest is coming in my next PR.  
The code is now also almost fully PEP8 compatible.  
Fixed up a few simple things like added requirements file and made it effective.  

*RDIL requested a review from @dowlandaiello and @xoreo*

### CODE REVIEW

**Comment by lexzaiello** [comment]
Did you just open an entire pull request just to make everything snake case?

**Comment by RDIL** [comment]
No.  PEP8 says function names should be snake case however.

**Comment by lexzaiello** [comment]
And, personally, I disagree with the PEP8.

**Comment by RDIL** [comment]
:(

**Comment by mattnappo** [comment]
And I prefer to use Golang standards.

**Comment by lexzaiello** [comment]
¯\\_(ツ)_/¯

**Comment by RDIL** [comment]
big sad

**Comment by dowlandaiello** [comment]
I do like the idea of adding documentation, though.

**Review by lexzaiello — DISMISSED** [review]
Love the idea of adding documentation. However, I'd remove all the camel-case to snake-case styling changes, as I personally prefer the Go language format specification for code styling, rather than PEP8.

**Review by RDIL — COMMENTED** [review]
K

**Comment by RDIL** [comment]
what the fuck I just resolved those conflicts

**Comment by RDIL** [comment]
there we go

**Comment by RDIL** [comment]
@dowlandaiello Please review again, I think I fixed it all.

**Comment by RDIL** [comment]
`SummerCash deleted a comment from RDIL a day ago`

**Comment by RDIL** [comment]
Its ready to merge, no conflicts, etc.

**Comment by RDIL** [comment]
Oh also heres a cool logo:
https://rdil.rocks/depression/summercash.JPG

**Comment by RDIL** [comment]
@dowlandaiello I know you're online, PR is ready

**Review by mattnappo — COMMENTED** [review]
I'm just going to close this out now. I don't think that this project needs much more work at all.

**Comment by RDIL** [comment]
How else are people going to know how to use it for without docs?

**Pull request closed without merging**
